title: My awesome blog noob
author: littlebru
email: brunaclegomes@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  My blog is incrible, and with the GithubLab I learning too much and fast XD love it

# social links
LinkedIn_username: Bruna Larissa Clemente Gomes # DO NOT include the @ character, or else the build will fail!
github_username:  littlebru # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
theme: minima
